Class {
	#name : #FamixFortranUnknownSourceLanguage,
	#superclass : #FamixFortranSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranUnknownSourceLanguage class >> annotation [

	<MSEClass: #UnknownSourceLanguage super: #FamixFortranSourceLanguage>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
