Class {
	#name : #FamixFortranIndexedFileAnchor,
	#superclass : #FamixFortranAbstractFileAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixFortranAbstractFileAnchor>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
