Class {
	#name : #FamixFortranFileAnchor,
	#superclass : #FamixFortranAbstractFileAnchor,
	#traits : 'FamixTFileNavigation',
	#classTraits : 'FamixTFileNavigation classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranFileAnchor class >> annotation [

	<FMClass: #FileAnchor super: #FamixFortranAbstractFileAnchor>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
