Class {
	#name : #FamixFortranMultipleFileAnchor,
	#superclass : #FamixFortranSourceAnchor,
	#traits : 'FamixTMultipleFileAnchor',
	#classTraits : 'FamixTMultipleFileAnchor classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranMultipleFileAnchor class >> annotation [

	<MSEClass: #MultipleFileAnchor super: #FamixFortranSourceAnchor>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
