Class {
	#name : #FamixFortranSourceLanguage,
	#superclass : #FamixFortranEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixFortranEntity>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
