Class {
	#name : #FamixFortranModel,
	#superclass : #MooseModel,
	#category : #'Famix-Fortran-Entities-Model'
}

{ #category : #accessing }
FamixFortranModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixFortranModel class >> annotation [
	<FMClass: #FamixFortranModel super: #MooseModel>
	<package: #'Famix-Fortran-Entities'>
	<generated>
]
