Class {
	#name : #FamixFortranAbstractFileAnchor,
	#superclass : #FamixFortranSourceAnchor,
	#traits : 'FamixTFileAnchor',
	#classTraits : 'FamixTFileAnchor classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranAbstractFileAnchor class >> annotation [

	<FMClass: #AbstractFileAnchor super: #FamixFortranSourceAnchor>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
