Class {
	#name : #FamixFortranSourceTextAnchor,
	#superclass : #FamixFortranSourceAnchor,
	#traits : 'FamixTWithImmediateSource',
	#classTraits : 'FamixTWithImmediateSource classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixFortranSourceAnchor>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
